//
//  ApiCurrecy.swift
//  CurrencyConverter24
//
//  Created by Borys Klykavka on 21.09.2024.
//

struct Currency: Hashable{
    let code: String
    let name: String
}

let currencies: [Currency] = [
    Currency(code: "AED", name: "UAE Dirham"),
    Currency(code: "AFN", name: "Afghan Afghani"),
    Currency(code: "ALL", name: "Albanian Lek"),
    Currency(code: "AMD", name: "Armenian Dram"),
    Currency(code: "ANG", name: "Netherlands Antillean Guilder"),
    Currency(code: "AOA", name: "Angolan Kwanza"),
    Currency(code: "ARS", name: "Argentine Peso"),
    Currency(code: "AUD", name: "Australian Dollar"),
    Currency(code: "AZN", name: "Azerbaijan Manat"),
    Currency(code: "BAM", name: "Bosnia And Herzegovina Convertible Mark"),
    Currency(code: "BBD", name: "Barbadian Dollar"),
    Currency(code: "BDT", name: "Bangladeshi Taka"),
    Currency(code: "BGN", name: "Bulgarian Lev"),
    Currency(code: "BHD", name: "Bahraini Dinar"),
    Currency(code: "BIF", name: "Burundi Franc"),
    Currency(code: "BIH", name: "Bosnia-Herzegovina Convertible Mark"),
    Currency(code: "BND", name: "Brunei Dollar"),
    Currency(code: "BOB", name: "Bolivian Boliviano"),
    Currency(code: "BRL", name: "Brazilian Real"),
    Currency(code: "BSD", name: "Bahamian Dollar"),
    Currency(code: "BTC", name: "Bitcoin"),
    Currency(code: "BTN", name: "Bhutanese Ngultrum"),
    Currency(code: "BYN", name: "Belarusian Ruble"),
    Currency(code: "BZD", name: "Belize Dollar"),
    Currency(code: "CAD", name: "Canadian Dollar"),
    Currency(code: "CDF", name: "Congolese Franc"),
    Currency(code: "CHF", name: "Swiss Franc"),
    Currency(code: "CLF", name: "Chilean Unit Of Account"),
    Currency(code: "CLP", name: "Chilean Peso"),
    Currency(code: "CNY", name: "Chinese Yuan Renminbi"),
    Currency(code: "COP", name: "Colombian Peso"),
    Currency(code: "CRC", name: "Costa Rican Colon"),
    Currency(code: "CVE", name: "Cape Verdean Escudo"),
    Currency(code: "CZK", name: "Czech Koruna"),
    Currency(code: "DJF", name: "Djiboutian Franc"),
    Currency(code: "DKK", name: "Danish Krone"),
    Currency(code: "DOP", name: "Dominican Peso"),
    Currency(code: "DZD", name: "Algerian Dinar"),
    Currency(code: "EGP", name: "Egyptian Pound"),
    Currency(code: "ERN", name: "Eritrean Nakfa"),
    Currency(code: "ETB", name: "Ethiopian Birr"),
    Currency(code: "ETH", name: "Ethereum"),
    Currency(code: "EUR", name: "European Euro"),
    Currency(code: "FJD", name: "Fijian Dollar"),
    Currency(code: "FKP", name: "Falkland Islands Pound"),
    Currency(code: "GBP", name: "Pound Sterling"),
    Currency(code: "GEL", name: "Georgian Lari"),
    Currency(code: "GHS", name: "Ghanaian Cedi"),
    Currency(code: "GIP", name: "Gibraltar Pound"),
    Currency(code: "GMD", name: "Gambian Dalasi"),
    Currency(code: "GNF", name: "Guinean Franc"),
    Currency(code: "GTQ", name: "Guatemalan Quetzal"),
    Currency(code: "GYD", name: "Guyanese Dollar"),
    Currency(code: "HKD", name: "Hong Kong Dollar"),
    Currency(code: "HNL", name: "Honduran Lempira"),
    Currency(code: "HRK", name: "Croatian Kuna"),
    Currency(code: "HTG", name: "Haitian Gourde"),
    Currency(code: "HUF", name: "Hungarian Forint"),
    Currency(code: "IDR", name: "Indonesian Rupiah"),
    Currency(code: "ILS", name: "Israeli New Shekel"),
    Currency(code: "INR", name: "Indian Rupee"),
    Currency(code: "IQD", name: "Iraqi Dinar"),
    Currency(code: "IRR", name: "Iranian Rial"),
    Currency(code: "ISK", name: "Icelandic Krona"),
    Currency(code: "JMD", name: "Jamaican Dollar"),
    Currency(code: "JOD", name: "Jordanian Dinar"),
    Currency(code: "JPY", name: "Japanese Yen"),
    Currency(code: "KES", name: "Kenyan Shilling"),
    Currency(code: "KGS", name: "Kyrgyzstani Som"),
    Currency(code: "KHR", name: "Cambodian Riel"),
    Currency(code: "KMF", name: "Comorian Franc"),
    Currency(code: "KRW", name: "South Korean Won"),
    Currency(code: "KWD", name: "Kuwaiti Dinar"),
    Currency(code: "KYD", name: "Cayman Islands Dollar"),
    Currency(code: "KZT", name: "Kazakhstani Tenge"),
    Currency(code: "LAK", name: "Lao Kip"),
    Currency(code: "LBP", name: "Lebanese Pound"),
    Currency(code: "LKR", name: "Sri Lankan Rupee"),
    Currency(code: "LRD", name: "Liberian Dollar"),
    Currency(code: "LSL", name: "Lesotho Loti"),
    Currency(code: "LYD", name: "Libyan Dinar"),
    Currency(code: "MAD", name: "Moroccan Dirham"),
    Currency(code: "MDL", name: "Moldovan Leu"),
    Currency(code: "MGA", name: "Malagasy Ariary"),
    Currency(code: "MKD", name: "Macedonian Denar"),
    Currency(code: "MMK", name: "Myanmar Kyat"),
    Currency(code: "MNT", name: "Mongolian Tugrik"),
    Currency(code: "MOP", name: "Macanese Pataca"),
    Currency(code: "MRO", name: "Mauritanian Ouguiya"),
    Currency(code: "MUR", name: "Mauritian Rupee"),
    Currency(code: "MVR", name: "Maldivian Rufiyaa"),
    Currency(code: "MWK", name: "Malawian Kwacha"),
    Currency(code: "MXN", name: "Mexican Peso"),
    Currency(code: "MYR", name: "Malaysian Ringgit"),
    Currency(code: "MZN", name: "Mozambican Metical"),
    Currency(code: "NAD", name: "Namibian Dollar"),
    Currency(code: "NGN", name: "Nigerian Naira"),
    Currency(code: "NIO", name: "Nicaraguan Cordoba"),
    Currency(code: "NOK", name: "Norwegian Krone"),
    Currency(code: "NPR", name: "Nepalese Rupee"),
    Currency(code: "NZD", name: "New Zealand Dollar"),
    Currency(code: "OMR", name: "Omani Rial"),
    Currency(code: "PAB", name: "Panamanian Balboa"),
    Currency(code: "PEN", name: "Peruvian Sol"),
    Currency(code: "PHP", name: "Philippine Peso"),
    Currency(code: "PKR", name: "Pakistani Rupee"),
    Currency(code: "PLN", name: "Polish Zloty"),
    Currency(code: "PYG", name: "Paraguayan Guarani"),
    Currency(code: "QAR", name: "Qatari Riyal"),
    Currency(code: "RON", name: "Romanian Leu"),
    Currency(code: "RSD", name: "Serbian Dinar"),
    Currency(code: "RUB", name: "Russian Ruble"),
    Currency(code: "RWF", name: "Rwandan Franc"),
    Currency(code: "SAR", name: "Saudi Arabian Riyal"),
    Currency(code: "SCR", name: "Seychellois Rupee"),
    Currency(code: "SDG", name: "Sudanese Pound"),
    Currency(code: "SEK", name: "Swedish Krona"),
    Currency(code: "SGD", name: "Singapore Dollar"),
    Currency(code: "SHP", name: "Saint Helena Pound"),
    Currency(code: "SLL", name: "Sierra Leonean Leone"),
    Currency(code: "SOS", name: "Somali Shilling"),
    Currency(code: "SRD", name: "Surinamese Dollar"),
    Currency(code: "STN", name: "Sao Tome And Principe Dobra"),
    Currency(code: "SVC", name: "Salvadoran Colón"),
    Currency(code: "SZL", name: "Swazi Lilangeni"),
    Currency(code: "THB", name: "Thai Baht"),
    Currency(code: "TJS", name: "Tajikistani Somoni"),
    Currency(code: "TMT", name: "Turkmen Manat"),
    Currency(code: "TND", name: "Tunisian Dinar"),
    Currency(code: "TOP", name: "Tongan Pa'anga"),
    Currency(code: "TRY", name: "Turkish Lira"),
    Currency(code: "TTD", name: "Trinidad And Tobago Dollar"),
    Currency(code: "TWD", name: "New Taiwan Dollar"),
    Currency(code: "TZS", name: "Tanzanian Shilling"),
    Currency(code: "UAH", name: "Ukrainian Hryvnia"),
    Currency(code: "UGX", name: "Ugandan Shilling"),
    Currency(code: "USD", name: "United States Dollar"),
    Currency(code: "UYU", name: "Uruguayan Peso"),
    Currency(code: "UZS", name: "Uzbekistani Som"),
    Currency(code: "VES", name: "Venezuelan Bolivar"),
    Currency(code: "VND", name: "Vietnamese Dong"),
    Currency(code: "VUV", name: "Vanuatu Vatu"),
    Currency(code: "WST", name: "Samoan Tala"),
    Currency(code: "XAF", name: "Central African CFA Franc"),
    Currency(code: "XCD", name: "East Caribbean Dollar"),
    Currency(code: "XOF", name: "West African CFA Franc"),
    Currency(code: "XPF", name: "CFP Franc"),
    Currency(code: "XRP", name: "Ripple"),
    Currency(code: "YER", name: "Yemeni Rial"),
    Currency(code: "ZAR", name: "South African Rand"),
    Currency(code: "ZMK", name: "Zambian Kwacha (pre-2013)"),
    Currency(code: "ZMW", name: "Zambian Kwacha")
]
